### ISSUE TITLE
Is there a way to change color of progress bar via options in js?

### ISSUE THREAD

**Issue by camohub** [jacoborus/nanobar#50]
Hi, is it possible to change color of progress bar via 	
````
var nanobar = new Nanobar( { barCss: {'background-color': 'green'  } );
````
I dont want to have it in less file.

**Comment by jacoborus** [comment]
No, it's not possible. But you can add a css line with javascript, nanobar is already doing that so you can use the same css tag:

```js
var s = document.getElementById('nanobarcss')
s.innerHTML = s.innerHTML + '.nanobar .bar{background:#bdf;}'
```

**Comment by camohub** [comment]
Can I ask you, why do you do it this way? Is it faster or what?

**Comment by jacoborus** [comment]
I don't do it this way, I use css:

```css
.nanobar .bar.errorbar {
  background: #e44;
}
```

**Comment by camohub** [comment]
Of course, but if it would be in settings option it would be at one place. That's all.

**Comment by oliveratgithub** [comment]
I had to use the following styling to style the nanobar progress bar correctly:

```css
.nanobar .bar { background-color: #0074d9; }
```
